[SIMDe]
git-tree-sha1 = "db342c5a68adbc45dc6076947b3cdca5acc00f77"

    [[SIMDe.download]]
    sha256 = "c2113c8cc87a1e0024d3aa9f7541ebba16caddfe584bae9ecf05c246857730ec"
    url = "https://github.com/JuliaBinaryWrappers/SIMDe_jll.jl/releases/download/SIMDe-v0.8.2+0/SIMDe.v0.8.2.any.tar.gz"
