# Autogenerated wrapper script for SIMDe_jll for any
JLLWrappers.@generate_wrapper_header("SIMDe")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
